CREATE DATABASE bookstore_db;
USE bookstore_db;
CREATE TABLE books(book_id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(100) NOT NULL,author VARCHAR(100),price DECIMAL(10,2),stock INT DEFAULT 0);
CREATE TABLE customers(customer_id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,phone VARCHAR(15),email VARCHAR(100));
CREATE TABLE orders(order_id INT AUTO_INCREMENT PRIMARY KEY,customer_id INT,total_amount DECIMAL(10,2),status VARCHAR(30),order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
